pulsecast:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      user: "{{ env_var('DBT_USER', 'pulsecast') }}"
      password: "{{ env_var('DBT_PASSWORD', 'pulsecast') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      dbname: "{{ env_var('DBT_DBNAME', 'pulsecast') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'public') }}"
      threads: 4
