version: 2

models:
  - name: inventory_parameters
    description: "Inventory parameters per SKU/location defining service level targets and policy inputs."
    columns:
      - name: sku_id
        description: "SKU identifier."
        tests:
          - not_null
      - name: location_id
        description: "Location identifier (nullable)."
      - name: service_level_target
        description: "Desired service level (0-1)."
      - name: lead_time_days
        description: "Lead time in days."
      - name: review_period_days
        description: "Review period in days."
      - name: min_order_qty
        description: "Minimum order quantity."
      - name: max_order_qty
        description: "Maximum order quantity."

  - name: inventory_recommendations
    description: "Optimizer outputs for inventory policies."
    columns:
      - name: policy_id
        description: "Primary key for recommendation."
        tests:
          - not_null
          - unique
      - name: sku_id
        description: "SKU identifier."
        tests:
          - not_null
      - name: location_id
        description: "Location identifier (nullable)."
      - name: year_month
        description: "Month of recommendation."
        tests:
          - not_null
      - name: source_type
        description: "Source type for policy (BASE_RUN, SCENARIO)."
        tests:
          - not_null
          - accepted_values:
              values: ["BASE_RUN", "SCENARIO"]
      - name: source_id
        description: "Run_id or scenario_id used to generate policy."
      - name: service_level_target
        description: "Service level applied."
      - name: safety_stock_units
        description: "Safety stock recommendation."
      - name: cycle_stock_units
        description: "Cycle stock recommendation."
      - name: target_stock_units
        description: "Total target stock (cycle + safety)."
      - name: created_at
        description: "Creation timestamp."
        tests:
          - not_null
    tests:
      - unique_combination:
          arguments:
            combination_of_columns: [sku_id, location_id, year_month, source_type, source_id]
